version: '3.5'

# 网络配置
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

# php 配置
configs:
  myphpconfig:
    file: ./php/extra.ini

services:
  php:
    container_name: php
    image: authus/php:7.4-phalcon
    working_dir: /var/www
    volumes:
      - ./src:${WORK_DIR}:delegated
      - ./log/php:/var/log/php/:rw
    configs:
      - source: myphpconfig
        target: /usr/local/etc/php/conf.d/extra.ini
    networks:
      - backend
    env_file:
      - .env

  mysql:
    container_name: mysql
    image: mariadb:latest # or mysql:5.7
    ports:
      - "${MYSQL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./log/mysql:/var/log/mysql/:rw
    restart: always
    networks:
      - backend
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend

  # postgres:
  #   container_name: postgres
  #   image: postgres:12-alpine
  #   privileged: true
  #   environment:
  #     - TZ=${TZ}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   ports:
  #     - "${POSTGRES_PORT}:5432"
  #   volumes:
  #     - ${DATA_PATH_HOST}/pgsql:/var/lib/postgresql/data
  #   restart: always

  redis:
    container_name: redis
    image: redis:5-alpine
    environment:
      - TZ=${TZ}
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    command: "redis-server --requirepass ${REDIS_PASSWORD}  --appendonly yes"
    privileged: true
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    networks:
      - backend
  
  memcached:
    container_name: memcached
    image: memcached:1.5-alpine
    networks:
      - backend
    ports:
      - "${MEMCACHED_PORT}:11211"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '${OPEN_PORT}:80'
    restart: on-failure
    volumes:
      - ./src:${WORK_DIR}
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx/:rw
    networks:
      - backend
    depends_on:
      - php
    links:
      - php